### ISSUE TITLE
Questions regarding bandwidth control

### ISSUE THREAD

**Issue by viswanathgs** [dcgym/iroko#28]
Hey Fabian, I have a few questions about the internals of the framework that I'm having trouble wrapping my head around. Hoping to get some clarify on the following:

1. I'm trying to understand the interaction between the tx_rate being enforced based on the policy by `BandwidthController` and how `cwnd` gets changed by the native congestion control algorithm in the TCP setting. I see that the way we enforce the action taken by the policy is by capping the bandwidth allocated to the interface (https://github.com/dcgym/iroko/blob/master/dc_gym/control/bw_control.c#L55). This makes sense for UDP, but in the TCP scenario, isn't the underlying congestion control algorithm also doing its own thing and potentially interfering with the bandwidth control?
2. Have you been able to, or is there a way to simulate bursts of traffic to simulate a more realistic setting? Based on what I understand from `iroko_traffic.py` (https://github.com/dcgym/iroko/blob/master/dc_gym/iroko_traffic.py#L174), we generate a constant stream of traffic from src to dst right?

Thanks!

**Comment by fruffy** [comment]
Hi Viswanath! 
Yeah both of these issues are still major pain points, unfortunately this platform is not very mature yet. 
 Some of the specific are explained in Section 4.1 [here](https://open.library.ubc.ca/cIRcle/collections/ubctheses/24/items/1.0378362). 
1. Right now, we do not adjust `cwnd` at all, instead we remotely configure the parameters of a `qdisc` on the interface. This is done by running `node_controller.c` on each host. The intention is to model something like [Carousel](https://www.cc.gatech.edu/~amsmti3/files/carousel-sigcomm17.pdf). The advantage of this technique is that it is agnostic of the transport protocol and we do not have to track all individual TCP connections. The `qdisc` manages fairness locally, that is where TCP comes in as a feature.  There are two challenges The lack of fine-grained control over sending rate and the fact that, as you described, the noise generated by TCP's agent might mess with the RL algorithms. 
Modifying the `cwnd` directly will likely require a kernel module, [CCP](https://ccp-project.github.io/), or some modification to traffic generators. All of this is definitely a possibility, but will require some more implementation work. CCP is quite an interesting project because it exposes a nice userspace API to configure TCP algorithms. There is lots of possibilities and a lot of work that can be done here. 

2. You are right, we are sending constant traffic currently. It is technically possible to simulate bursts and random traffic but I haven't fully implemented it yet. This is on my todo list, Section 4.13. has some details on the traffic generation. Basically, the traffic generator will just ingest an configuration file like [this](https://github.com/dcgym/iroko/blob/master/dc_gym/inputs/dumbbell/incast_4) one, which specifies the length of individual flows, gaps between them, and randomness. This is actually a slightly modified version of this module: [cluster_loadgen ](https://github.com/mininet/mininet-tests/tree/master/hedera/hedera/cluster_loadgen).

Hope that answers your questions!
Fabian

**Comment by viswanathgs** [comment]
Thanks for the reply Fabian!

1. On this, I have thus far noticed improved performance when PPO is run on TCP compared to UDP on both dumbbell and fattree topologies, and the likely explanation is what you mentioned - the interference of the underlying TCP agent. RL on UDP seems like a fairer experimental setup given this, but when we compare that with DCTCP, the CC algorithm isn't the only thing that's different (due to the underlying transport itself being different). QUIC seems like a much better choice for experimentation as you can actually control just the CC algorithm directly. Have you thought about that?
2. This would be super useful!

Cheers!
Viswanath

**Comment by fruffy** [comment]
1. Yeah I think a major issue is the level of control the agents currently have. There is a significant delay and imprecision in action enforcement, which make the experiments unnecessarily hard for an RL agent. Manipulating the cwnd and rate control of individual streams directly would be nice, but complexity will likely explode with that. I have been thinking of a hierarchical approach where you train a congestion model locally on each host and optimize locally. That could work really well.
QUIC as a logical extension of the UDP transport could also be really nice. Since the traffic generator is already in Go, integration should not be too difficult. Definitely something to try out. A lot of this is just implementation work. 

2. Hope to get this done soon
